helmDefaults:
  wait: true
  timeout: 300
  atomic: true

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: myapp
    namespace: my-namespace
    chart: bitnami/nginx
    version: 15.3.2
    values:
      - values/myapp-values.yaml
