apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-dynamic-elements-json
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/34fathombelow/akuity-examples.git
    targetRevision: main
    path: dynamic-elements/example
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd