apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-helm-lookup
  namespace: argocd
spec:
  destination:
    namespace: guestbook-helmlookup
    name: temp
  source:
    path: helm-lookup/example
    repoURL: https://github.com/34fathombelow/akuity-examples.git
    targetRevision: main
    plugin:
      name: helm-lookup
      env:
        - name: HELM_RESPECT_CHART_NAMESPACE
          value: "false"
      parameters:
        - array:
            - stage.yaml
          name: values-files
        - name: releaseName
          string: custom-name
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
