apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helmfile-private-chart-sops
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/34fathombelow/akuity-examples.git
    targetRevision: main
    path: helmfile/private_helm_chart_sops
  destination:
    name: in-cluster
    namespace: argocd