apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-list-generator
  namespace: app-in-any-namespace
spec:
  generators:
  - list:
      elements:
      - name: test
        namespace: test
        server: http://cluster-test:8001
      - name: prod
        namespace: prod
        server: http://cluster-prod:8001
      - name: dev
        namespace: dev
        server: http://cluster-dev:8001
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
  goTemplate: true
  goTemplateOptions:
  - missingkey=error
  syncPolicy:
    applicationsSync: sync
    preserveResourcesOnDeletion: true
  template:
    metadata:
      annotations:
        kargo.akuity.io/authorized-stage: semver:first
        notifications.argoproj.io/subscribe.on-deployed-git.github: ""
      name: '{{.name}}-guestbook'
      namespace: app-in-any-namespace
    spec:
      destination:
        namespace: '{{.namespace}}'
        server: '{{.server}}'
      project: app-in-any-namespace
      source:
        path: guestbook
        repoURL: https://github.com/34fathombelow/argocd-example-apps.git
        targetRevision: testing
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
        - CreateNamespace=true
