apiVersion: apps/v1
kind: Deployment
metadata:
  name: sinkhole-200
  namespace: akuity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sinkhole-200
  template:
    metadata:
      labels:
        app: sinkhole-200
    spec:
      containers:
        - name: sink
          image: hashicorp/http-echo:1.0
          args: ["-text={\"ok\":true}"]
          ports:
            - name: http
              containerPort: 5678
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: sinkhole-200
  namespace: akuity
spec:
  selector:
    app: sinkhole-200
  ports:
    - name: http
      port: 80
      targetPort: 5678
  type: ClusterIP
