{{- $ns := lookup "v1" "Namespace" "" "akuity" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-lookup-configmap
data:
  helm-lookup-cluster-name: {{ index $ns.metadata.labels "akuity.io/argo-cd-cluster-name" | default "unknown" }}
