apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-in-any-namepsace-app-of-apps
  namespace: argocd
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-in-any-namespace/example
    repoURL: https://github.com/34fathombelow/akuity-examples.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}